Update flutter-build.yml

diff --git a/.github/workflows/flutter-build.yml b/.github/workflows/flutter-build.yml
--- a/.github/workflows/flutter-build.yml
+++ b/.github/workflows/flutter-build.yml
@@ -614,152 +614,152 @@ jobs:
           files: |
             signed-apk/rustdesk-${{ env.VERSION }}-${{ matrix.job.arch }}.apk
 
-  build-rustdesk-lib-linux-amd64:
-    needs: [generate-bridge-linux, build-vcpkg-deps-linux]
-    name: build-rust-lib ${{ matrix.job.target }} (${{ matrix.job.os }}) [${{ matrix.job.extra-build-features }}]
-    runs-on: ${{ matrix.job.os }}
-    strategy:
-      fail-fast: false
-      matrix:
-        # use a high level qemu-user-static
-        job:
-          # - { target: i686-unknown-linux-gnu      , os: ubuntu-20.04, use-cross: true }
-          # - { target: i686-unknown-linux-musl     , os: ubuntu-20.04, use-cross: true }
-          - {
-              arch: x86_64,
-              target: x86_64-unknown-linux-gnu,
-              os: ubuntu-20.04,
-              extra-build-features: "",
-              enable-headless: true
-            }
-          - {
-              arch: x86_64,
-              target: x86_64-unknown-linux-gnu,
-              os: ubuntu-20.04,
-              extra-build-features: "flatpak",
-              enable-headless: false
-            }
-          - {
-              arch: x86_64,
-              target: x86_64-unknown-linux-gnu,
-              os: ubuntu-20.04,
-              extra-build-features: "appimage",
-              enable-headless: false
-            }
-          # - { target: x86_64-unknown-linux-musl   , os: ubuntu-20.04, use-cross: true }
-    steps:
-      - name: Maximize build space
-        run: |
-          sudo rm -rf /opt/ghc
-          sudo rm -rf /usr/local/lib/android
-          sudo rm -rf /usr/share/dotnet
-          sudo apt update -y
-          sudo apt install qemu-user-static
+  # build-rustdesk-lib-linux-amd64:
+  #   needs: [generate-bridge-linux, build-vcpkg-deps-linux]
+  #   name: build-rust-lib ${{ matrix.job.target }} (${{ matrix.job.os }}) [${{ matrix.job.extra-build-features }}]
+  #   runs-on: ${{ matrix.job.os }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       # use a high level qemu-user-static
+  #       job:
+  #         # - { target: i686-unknown-linux-gnu      , os: ubuntu-20.04, use-cross: true }
+  #         # - { target: i686-unknown-linux-musl     , os: ubuntu-20.04, use-cross: true }
+  #         - {
+  #             arch: x86_64,
+  #             target: x86_64-unknown-linux-gnu,
+  #             os: ubuntu-20.04,
+  #             extra-build-features: "",
+  #             enable-headless: true
+  #           }
+  #         - {
+  #             arch: x86_64,
+  #             target: x86_64-unknown-linux-gnu,
+  #             os: ubuntu-20.04,
+  #             extra-build-features: "flatpak",
+  #             enable-headless: false
+  #           }
+  #         - {
+  #             arch: x86_64,
+  #             target: x86_64-unknown-linux-gnu,
+  #             os: ubuntu-20.04,
+  #             extra-build-features: "appimage",
+  #             enable-headless: false
+  #           }
+  #         # - { target: x86_64-unknown-linux-musl   , os: ubuntu-20.04, use-cross: true }
+  #   steps:
+  #     - name: Maximize build space
+  #       run: |
+  #         sudo rm -rf /opt/ghc
+  #         sudo rm -rf /usr/local/lib/android
+  #         sudo rm -rf /usr/share/dotnet
+  #         sudo apt update -y
+  #         sudo apt install qemu-user-static
 
-      - name: Checkout source code
-        uses: actions/checkout@v3
+  #     - name: Checkout source code
+  #       uses: actions/checkout@v3
 
-      - name: Set Swap Space
-        uses: pierotofy/set-swap-space@master
-        with:
-          swap-size-gb: 12
+  #     - name: Set Swap Space
+  #       uses: pierotofy/set-swap-space@master
+  #       with:
+  #         swap-size-gb: 12
 
-      - name: Free Space
-        run: |
-          df
+  #     - name: Free Space
+  #       run: |
+  #         df
 
-      - name: Install Rust toolchain
-        uses: actions-rs/toolchain@v1
-        with:
-          toolchain: stable
-          target: ${{ matrix.job.target }}
-          override: true
-          profile: minimal # minimal component installation (ie, no documentation)
+  #     - name: Install Rust toolchain
+  #       uses: actions-rs/toolchain@v1
+  #       with:
+  #         toolchain: stable
+  #         target: ${{ matrix.job.target }}
+  #         override: true
+  #         profile: minimal # minimal component installation (ie, no documentation)
       
-      - name: Save Rust toolchain version
-        run: |
-          RUST_TOOLCHAIN_VERSION=$(cargo --version | awk '{print $2}')
-          echo "RUST_TOOLCHAIN_VERSION=$RUST_TOOLCHAIN_VERSION" >> $GITHUB_ENV
+  #     - name: Save Rust toolchain version
+  #       run: |
+  #         RUST_TOOLCHAIN_VERSION=$(cargo --version | awk '{print $2}')
+  #         echo "RUST_TOOLCHAIN_VERSION=$RUST_TOOLCHAIN_VERSION" >> $GITHUB_ENV
 
-      - name: Disable rust bridge build
-        run: |
-          # only build cdylib
-          sed -i  "s/\[\"cdylib\", \"staticlib\", \"rlib\"\]/\[\"cdylib\"\]/g" Cargo.toml
+  #     - name: Disable rust bridge build
+  #       run: |
+  #         # only build cdylib
+  #         sed -i  "s/\[\"cdylib\", \"staticlib\", \"rlib\"\]/\[\"cdylib\"\]/g" Cargo.toml
 
-      - name: Restore bridge files
-        uses: actions/download-artifact@master
-        with:
-          name: bridge-artifact
-          path: ./
+  #     - name: Restore bridge files
+  #       uses: actions/download-artifact@master
+  #       with:
+  #         name: bridge-artifact
+  #         path: ./
 
-      - name: Restore vcpkg files
-        uses: actions/download-artifact@master
-        with:
-          name: vcpkg-artifact-${{ matrix.job.arch }}
-          path: /opt/artifacts/vcpkg/installed
+  #     - name: Restore vcpkg files
+  #       uses: actions/download-artifact@master
+  #       with:
+  #         name: vcpkg-artifact-${{ matrix.job.arch }}
+  #         path: /opt/artifacts/vcpkg/installed
 
-      - uses: rustdesk-org/run-on-arch-action@amd64-support
-        name: Build rustdesk library for ${{ matrix.job.arch }}
-        id: vcpkg
-        with:
-          arch: ${{ matrix.job.arch }}
-          distro: ubuntu18.04
-          # not ready yet
-          # distro: ubuntu18.04-rustdesk
-          githubToken: ${{ github.token }}
-          setup: |
-            ls -l "${PWD}"
-            ls -l /opt/artifacts/vcpkg/installed
-          dockerRunArgs: |
-            --volume "${PWD}:/workspace"
-            --volume "/opt/artifacts:/opt/artifacts"
-          shell: /bin/bash
-          install: |
-            apt update -y
-            echo -e "installing deps"
-            apt-get -qq install -y  git curl wget nasm yasm libgtk-3-dev clang libxcb-randr0-dev libxdo-dev libxfixes-dev libxcb-shape0-dev libxcb-xfixes0-dev libasound2-dev libpulse-dev cmake libclang-dev ninja-build libappindicator3-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libvdpau-dev libva-dev libpam0g-dev libclang-dev llvm-dev libclang-10-dev llvm-10-dev pkg-config tree g++ gcc libvpx-dev tree > /dev/null
-            # we have libopus compiled by us.
-            apt remove -y libopus-dev || true
-            # output devs
-            ls -l ./
-            tree -L 3 /opt/artifacts/vcpkg/installed
-          run: |
-            # disable git safe.directory
-            git config --global --add safe.directory "*"
-            # rust
-            pushd /opt
-            # do not use rustup, because memory overflow in qemu
-            wget -O rust.tar.gz https://static.rust-lang.org/dist/rust-${{env.RUST_TOOLCHAIN_VERSION}}-${{ matrix.job.target }}.tar.gz
-            tar -zxvf rust.tar.gz > /dev/null && rm rust.tar.gz
-            cd rust-${{env.RUST_TOOLCHAIN_VERSION}}-${{ matrix.job.target }} && ./install.sh
-            rm -rf rust-${{env.RUST_TOOLCHAIN_VERSION}}-${{ matrix.job.target }}
-            # edit config
-            mkdir -p ~/.cargo/
-            echo """
-              [source.crates-io]
-              registry = 'https://github.com/rust-lang/crates.io-index'
-            """ > ~/.cargo/config
-            cat ~/.cargo/config
-            # start build
-            pushd /workspace
-            # mock 
-            case "${{ matrix.job.arch }}" in
-              x86_64)
-                # no need mock on x86_64
-                export VCPKG_ROOT=/opt/artifacts/vcpkg
-                export DEFAULT_FEAT=""
-                if ${{ matrix.job.enable-headless }}; then
-                  export DEFAULT_FEAT=linux_headless
-                fi
-                cargo build --lib --features hwcodec,flutter,flutter_texture_render,${{ matrix.job.extra-build-features }},$DEFAULT_FEAT --release
-                ;;
-            esac
+  #     - uses: rustdesk-org/run-on-arch-action@amd64-support
+  #       name: Build rustdesk library for ${{ matrix.job.arch }}
+  #       id: vcpkg
+  #       with:
+  #         arch: ${{ matrix.job.arch }}
+  #         distro: ubuntu18.04
+  #         # not ready yet
+  #         # distro: ubuntu18.04-rustdesk
+  #         githubToken: ${{ github.token }}
+  #         setup: |
+  #           ls -l "${PWD}"
+  #           ls -l /opt/artifacts/vcpkg/installed
+  #         dockerRunArgs: |
+  #           --volume "${PWD}:/workspace"
+  #           --volume "/opt/artifacts:/opt/artifacts"
+  #         shell: /bin/bash
+  #         install: |
+  #           apt update -y
+  #           echo -e "installing deps"
+  #           apt-get -qq install -y  git curl wget nasm yasm libgtk-3-dev clang libxcb-randr0-dev libxdo-dev libxfixes-dev libxcb-shape0-dev libxcb-xfixes0-dev libasound2-dev libpulse-dev cmake libclang-dev ninja-build libappindicator3-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libvdpau-dev libva-dev libpam0g-dev libclang-dev llvm-dev libclang-10-dev llvm-10-dev pkg-config tree g++ gcc libvpx-dev tree > /dev/null
+  #           # we have libopus compiled by us.
+  #           apt remove -y libopus-dev || true
+  #           # output devs
+  #           ls -l ./
+  #           tree -L 3 /opt/artifacts/vcpkg/installed
+  #         run: |
+  #           # disable git safe.directory
+  #           git config --global --add safe.directory "*"
+  #           # rust
+  #           pushd /opt
+  #           # do not use rustup, because memory overflow in qemu
+  #           wget -O rust.tar.gz https://static.rust-lang.org/dist/rust-${{env.RUST_TOOLCHAIN_VERSION}}-${{ matrix.job.target }}.tar.gz
+  #           tar -zxvf rust.tar.gz > /dev/null && rm rust.tar.gz
+  #           cd rust-${{env.RUST_TOOLCHAIN_VERSION}}-${{ matrix.job.target }} && ./install.sh
+  #           rm -rf rust-${{env.RUST_TOOLCHAIN_VERSION}}-${{ matrix.job.target }}
+  #           # edit config
+  #           mkdir -p ~/.cargo/
+  #           echo """
+  #             [source.crates-io]
+  #             registry = 'https://github.com/rust-lang/crates.io-index'
+  #           """ > ~/.cargo/config
+  #           cat ~/.cargo/config
+  #           # start build
+  #           pushd /workspace
+  #           # mock 
+  #           case "${{ matrix.job.arch }}" in
+  #             x86_64)
+  #               # no need mock on x86_64
+  #               export VCPKG_ROOT=/opt/artifacts/vcpkg
+  #               export DEFAULT_FEAT=""
+  #               if ${{ matrix.job.enable-headless }}; then
+  #                 export DEFAULT_FEAT=linux_headless
+  #               fi
+  #               cargo build --lib --features hwcodec,flutter,flutter_texture_render,${{ matrix.job.extra-build-features }},$DEFAULT_FEAT --release
+  #               ;;
+  #           esac
 
-      - name: Upload Artifacts
-        uses: actions/upload-artifact@master
-        with:
-          name: librustdesk-${{ matrix.job.arch }}-${{ matrix.job.extra-build-features }}.so
-          path: target/release/liblibrustdesk.so
+  #     - name: Upload Artifacts
+  #       uses: actions/upload-artifact@master
+  #       with:
+  #         name: librustdesk-${{ matrix.job.arch }}-${{ matrix.job.extra-build-features }}.so
+  #         path: target/release/liblibrustdesk.so
 
   # build-rustdesk-lib-linux-arm:
   #   if: ${{ inputs.upload-artifact }}
